# template/site.yaml

title: easel
author: Full Name
copyright: © 2020 Full Name
favicon:

menu:
- type: section
  label: page types

- type: spacer
  size: small

- type: link-page
  label: lazy
  links-to: page-lazy

- type: link-page
  label: lazy (gallery)
  links-to: page-lazy-gallery

- type: link-page
  label: layout
  links-to: page-layout

- type: link-page
  label: layout (gallery)
  links-to: page-layout-gallery

- type: link-page
  label: markdown
  links-to: page-markdown

- type: spacer
  size: medium

- type: link-url
  label: link
  url: http://www.link.com

theme:
  menu:
    width:
    align:
    header:
      label: easel
      image:
        path:
        width:
        height:
  page:
    width:
    align:
  colors:
    accent-base:
    accent-light:

extras: {}
