# template/site.yaml

title: easel
author: Full Name
copyright: © 2020 Full Name
favicon:

menu:
- type: link-page
  label: lazy
  links-to: pages/page-lazy

- type: link-page
  label: lazy (gallery)
  links-to: pages/page-lazy-gallery

- type: link-page
  label: layout
  links-to: pages/page-layout

- type: link-page
  label: layout (gallery)
  links-to: pages/page-layout-gallery

- type: link-page
  label: markdown
  links-to: pages/page-markdown

- type: spacer
  label:
  size: medium

- type: link-url
  label: link
  url: http://www.link.com

header:
  title: easel
  image:
    path:
    width:
    height:

theme:
  name: sargent
