# snapshots/site.yaml

title: snapshots
author: Full Name
copyright: © 2020 Full Name
favicon:

menu:
- type: link-page
  label: nature
  links-to: pages/nature
- type: link-page
  label: patterns
  links-to: pages/patterns
- type: link-page
  label: people
  links-to: pages/people
- type: spacer
  size: small
- type: link-url
  label: link
  url: http://www.link.com

header:
  title: snapshots
  image:
    path:
    width:
    height:

theme:
  name: sargent
