# testing-demo/site.yaml

title: Testing Demo
author: Testing Full Name
copyright: © 2020 Testing Full Name
description: A demo for Testing Easel.

menu:
  - type: link-page
    label: Images
    links-to: ./contents/pages/images

  - type: link-page
    label: TextBlock
    links-to: ./contents/pages/text-block

  - type: link-page
    label: Markdown
    links-to: ./contents/pages/markdown

  - type: link-page
    label: Embedded
    links-to: ./contents/pages/embedded

header:
  title:
    label: Testing Demo