# testing-demo/site.yaml

title: Testing Demo
author: Testing Full Name
copyright: © 2020 Testing Full Name
description: A demo for Testing Easel.

menu:
  - type: link-page
    label: Nature
    links-to: ./contents/pages/testing-nature

  - type: link-page
    label: Embedded
    links-to: ./contents/pages/testing-embedded

header:
  title: Testing Demo
