# sorolla-demo/site.yaml

title: Joaquín Sorolla
author: Full Name
copyright: © 2020 Full Name
description: A demo of the 'Sargent' theme for Easel.

menu:
- type: link-page
  label: Nature
  links-to: ./contents/pages/nature

- type: link-page
  label: Patterns
  links-to: ./contents/pages/patterns

- type: link-page
  label: Places
  links-to: ./contents/pages/places

- type: link-page
  label: Food
  links-to: ./contents/pages/food

- type: spacer
  size: small

- type: link-page
  label: About
  links-to: ./contents/pages/about


header:
  title:
    label: Joaquín Sorolla
